#!/bin/bash
# Setup: Run "source setup $ENV", where ENV is the directory you want to put the virtual environment

if [ -z $1 ]; then
    envdir="env"
else
    envdir=$1
fi

if ! [ -d $envdir ]; then
    virtualenv $envdir --distribute --no-site-packages
    echo "Installed virtualenv to ./${envdir}"
fi

source ${envdir}/bin/activate
echo "Installing any missing packages from requirements.txt"
pip install -q -r requirements.txt
